# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  database: savoir_development
  pool: 5
  username: postgres
  password: root

test:
  adapter: postgresql
  database: savoir_test
  pool: 5
  timeout: 5000
  username: postgres
  password: root

production:
  adapter: postgresql
  database: deploy
  pool: 5
  timeout: 5000
  username: deploy
  password: P8WtxZ3Xwt